version: '1.0'

actions:
  - action: 'Build Docker image'
    type: 'DOCKER_BUILD'
    image_name: 'your-docker-image-name'
    dockerfile_path: '.'
    build_context: '.'
    push_image: true
    registry: 'docker.io'
    username: '${eycasa}'
    password: '${G4nd4lph!}'

triggers:
  - action: 'Build Docker image'
    event_type: 'PUSH'
    ref: 'refs/heads/main'
    branch: 'main'
    push_patterns:
      - 'Dockerfile'
      - '*.sh'
    push_source: 'GITHUB'
    push_target: 'DOCKER'
    only_paths: ['.']
  