name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.eycasa }} -p ${{ secrets.G4nd4lph! }}
      - run: docker build -t eycasa/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true eycasa/react-test npm test
 
      - run: docker build -t eycasa/multi-client-10-14 ./client
      - run: docker build -t eycasa/multi-nginx-10-14 ./nginx
      - run: docker build -t eycasa/multi-server-10-14 ./server
      - run: docker build -t eycasa/multi-worker-10-14 ./worker
 
      - run: docker push eycasa/multi-client-10-14
      - run: docker push eycasa/multi-nginx-10-14
      - run: docker push eycasa/multi-server-10-14
      - run: docker push eycasa/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: eycasa/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.G4nd4lph! }}
          aws_secret_key: ${{ secrets.Gh1ml1?! }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-central-1
          region: eu-central-1-7398-9465-7397
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip